apiVersion: v1
kind: Service
metadata:
  namespace: eda
  labels:
    app: kafka
  name:  kafka-svc
spec:
  type: LoadBalancer
  selector:
    app: kafka
    id: "0"
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  
  
