apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: eda
  name: nginx-ingress
spec:
  rules:
    - port: 30000
      http:
        paths:
          - backend: 
              serviceName: nginx-svc
              servicePort: 30080 
---
apiVersion: v1
kind: Service
metadata:
  namespace: eda
  labels:
    app: nginx-svc
  name:  nginx-svc
spec:
  type: LoadBalancer
  ports:
    - name: nginx-port
      port: 8080
      nodePort: 30080
      targetPort: 8080
  selector:
    app: api-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eda
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-nginx
  template:
    metadata:
      labels:
        app: api-nginx
    spec:
      containers:
      - name: web1
        image: docker.io/nginx:alpine
        ports:
        - containerPort: 8080
        