version: '3.9'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    hostname: eda-prd-zookeeper
    container_name: eda-prd-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - eda-prd-sandbox

  kafka1:
    image: docker.io/bitnami/kafka:3.1
    hostname: eda-prd-kafka-01
    container_name: eda-prd-kafka-01
    environment:
      KAFKA_BROKER_ID: '0'
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'eda-prd-zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://eda-prd-kafka-01:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://eda-prd-kafka-01:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'
      KAFKA_NUM_PARTITIONS: '2'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
    networks:
      - eda-prd-sandbox
    depends_on:
      - zookeeper

  kafka2:
    image: docker.io/bitnami/kafka:3.1
    hostname: eda-prd-kafka-02
    container_name: eda-prd-kafka-02
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'eda-prd-zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://eda-prd-kafka-02:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://eda-prd-kafka-02:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'
      KAFKA_NUM_PARTITIONS: '2'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
    networks:
      - eda-prd-sandbox
    depends_on:
      - zookeeper

  kafka3:
    image: docker.io/bitnami/kafka:3.1
    hostname: eda-prd-kafka-03
    container_name: eda-prd-kafka-03
    environment:
      KAFKA_BROKER_ID: '2'
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'eda-prd-zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://eda-prd-kafka-03:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://eda-prd-kafka-03:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'
      KAFKA_NUM_PARTITIONS: '2'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
    networks:
      - eda-prd-sandbox
    depends_on:
      - zookeeper

  rabbit:
    hostname: eda-prd-rabbit
    container_name: eda-prd-rabbit
    image: docker.io/rabbitmq:3.9.14-management
    # ports: 
    #   - 15672:15672
    networks:
      - eda-prd-sandbox
  
  flagd:
    image: ghcr.io/open-feature/flagd:v0.3.6
    container_name: eda-prd-flagd
    hostname: eda-prd-flagd
    command:
      - start
      - --uri
      - https://raw.githubusercontent.com/robsondouglas/eda-sandbox/main/.prod/flags.json
    networks:
      - eda-prd-sandbox
    expose: 
      - "8013"

  membd:
    hostname: eda-prd-membd
    container_name: eda-prd-membd
    image: docker.io/robsondouglas/eda-sandbox-bdmem:latest
    ports: 
      - 5050:5050
    environment:
      WRITE_LOG: 1
      PORT_NUMBER: 5050
    networks:
      - eda-prd-sandbox

  ws:
    hostname: eda-prd-ws
    container_name: eda-prd-ws
    image: docker.io/robsondouglas/eda-sandbox-websocket:latest    
    environment:
      WRITE_LOG: 1
      PORT_NUMBER: 5051
    networks:
      - eda-prd-sandbox

  apivote:
    hostname: eda-prd-api-vote
    container_name: eda-prd-api-vote
    image: docker.io/robsondouglas/eda-sandbox-apivote:latest
    ports:
      - 5052:5052
    environment:
      WRITE_LOG: 1
      PORT_NUMBER: 5052 #porta que a api vai utilizar pra disponibilizar o serviço http
      QUEUE_URL: amqp://eda-prd-rabbit
      DB_URL:  http://eda-prd-membd:5050/bd
      FLAGD_HOST: eda-prd-flagd
    depends_on:
      - membd
      - rabbit
      - flagd
    networks:
      - eda-prd-sandbox

  wrkvote:
    hostname: eda-prd-wrk-vote
    container_name: eda-prd-wrk-vote
    image: docker.io/robsondouglas/eda-sandbox-workervote:latest
    environment:
      WRITE_LOG: 1
      KAFKA_SERVER: "eda-prd-kafka-01:29092, eda-prd-kafka-02:29093, eda-prd-kafka-03:29094"
      KAFKA_GROUP_ID: "eda-prd-01"
      QUEUE_URL: amqp://eda-prd-rabbit
      DB_URL:  http://eda-prd-membd:5050/bd
      WS_URL:  http://eda-prd-ws:5051/
    networks:
      - eda-prd-sandbox
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - rabbit
      - membd

  wrkaggr:
    hostname: eda-prd-wrk-aggr
    container_name: eda-prd-wrk-aggr
    image: docker.io/robsondouglas/eda-sandbox-workeraggregator:latest 
    environment:
      WRITE_LOG: 1
      KAFKA_SERVER: "eda-prd-kafka-01:29092, eda-prd-kafka-02:29093, eda-prd-kafka-03:29094"
      KAFKA_GROUP_ID: "eda-prd-01"
      DB_URL:  http://eda-prd-membd:5050/bd
      WS_URL:  http://eda-prd-ws:5051/
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - ws
      - membd
    networks:
      - eda-prd-sandbox
  
  front-angular:
    hostname: eda-prd-angular
    container_name: eda-prd-angular
    image: docker.io/robsondouglas/eda-front-angular:latest
    ports:
      - 9000:80 #bind da porta que a api vai utilizar pra disponibilizar o serviço http
    environment:
      WS_URL: http://eda-prd-ws:5051/socket.io/
      API_URL: http://eda-prd-api-vote:5052/      
    networks:
      - eda-prd-sandbox
    depends_on:
      - ws
      - apivote
      - flagd

networks:
  eda-prd-sandbox:
    driver: bridge