version: '3.9'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    hostname: eda-zookeeper
    container_name: eda-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - eda-sandbox

  kafka1:
    image: docker.io/bitnami/kafka:3.1
    hostname: eda-kafka-01
    container_name: eda-kafka-01
    environment:
      KAFKA_BROKER_ID: '0'
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'eda-zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://eda-kafka-01:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://eda-kafka-01:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'
      KAFKA_NUM_PARTITIONS: '2'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
    networks:
      - eda-sandbox
    depends_on:
      - zookeeper

  kafka2:
    image: docker.io/bitnami/kafka:3.1
    hostname: eda-kafka-02
    container_name: eda-kafka-02
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'eda-zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://eda-kafka-02:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://eda-kafka-02:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'
      KAFKA_NUM_PARTITIONS: '2'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
    networks:
      - eda-sandbox
    depends_on:
      - zookeeper

  kafka3:
    image: docker.io/bitnami/kafka:3.1
    hostname: eda-kafka-03
    container_name: eda-kafka-03
    environment:
      KAFKA_BROKER_ID: '2'
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'eda-zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://eda-kafka-03:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://eda-kafka-03:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'
      KAFKA_NUM_PARTITIONS: '2'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
    networks:
      - eda-sandbox
    depends_on:
      - zookeeper

  rabbit:
    image: docker.io/rabbitmq:3.9.14-management
    container_name: eda-rabbit
    # ports: 
    #   - 15672:15672
    networks:
      - eda-sandbox
  
  source:
    image: node:17
    container_name: eda-source
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace/source
    networks:
      - eda-sandbox

networks:
  eda-sandbox:
    driver: bridge 

