FROM node:17

ARG app_name

WORKDIR /usr/api

COPY webpack.config.js .
COPY package.json .
RUN npm i

COPY src/ ./src
RUN npm run $app_name
RUN rm -rf src/
RUN rm -rf webpack.config.js
RUN rm -rf package.json

WORKDIR /usr/api/dist
CMD node index.js